# (физический диапазон хода серво)
eyes_pan:   { min: 60, max: 120, center: 90 }
eyes_tilt:  { min: 70, max: 110, center: 90 }
lid_tl:     { min: 0, max: 60, open: 60, closed: 0 }
lid_tr:     { min: 0, max: 58, open: 0, closed: 58 }
lid_bl:     { min: 0, max: 50, open: 0, closed: 50 }
lid_br:     { min: 0, max: 54, open: 54, closed: 0 }

mouth:      { min: 0, max: 30, center: 0 }